#!/usr/bin/env node

'use strict';

const chalk = require('chalk');
const execSync = require('child_process').execSync;
const fs = require('fs');
const os = require('os');
const path = require('path');
const program = require('commander');

program
    .action(action);

function action(templateName) {

    const templatesDir = path.join(os.homedir(), '.scaffold-it');
    try {
        execSync(`git pull origin HEAD`, { stdio:'inherit', cwd: path.join(templatesDir, templateName) });
    } catch (e) {
        console.log(chalk.red(e));
    }
}

program.parse(process.argv);
