#!/usr/bin/env node

'use strict';

const chalk = require('chalk');
const fs = require('fs');
const mkdirp = require('mkdirp');
const os = require('os');
const path = require('path');
const program = require('commander');


    const templatesDir = path.join(os.homedir(), '.scaffold-it');
    mkdirp.sync(templatesDir);

    console.log(chalk.yellow(`Templates are in ${templatesDir}`));
    getDirs(templatesDir)
        .forEach(pathToDir => {
            console.log(chalk.green(path.basename(pathToDir)));
        });

function getDirs(pathToDir) {
    return fs.readdirSync(pathToDir)
        .filter(file =>
            fs.statSync(path.join(pathToDir, file)).isDirectory());
}

