#!/usr/bin/env node
'use strict';

const chalk = require('chalk');
const program = require('commander');
const version = require('./package.json').version;

program
    .version(version)
    .command('install <source>', 'Install a template from a git endpoint')
    .command('list', 'List all installed template')
    .command('template <template-name> <destination>', 'Run the templating program', {isDefault: true})
    .command('update <template-name>', 'Update a template by doing a pull')
    .parse(process.argv);
